name: dartsv
description: Dart Library for interacting with the Bitcoin network. This library is especially well-suited for use in developing Flutter applications.
version: 0.4.3
homepage: https://github.com/twostack/dartsv

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hex: ^0.2.0
  resource_portable: ^3.0.0
  pointycastle: ^3.5.1
  collection: ^1.15.0
  sprintf: ^6.0.0
  unorm_dart: ^0.2.0
  buffer: ^1.1.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
  mockito: ^5.1.0
